version: '3'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - sensor_static:/home/app/sensor/static
      - sensor_media:/home/app/sensor/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  sensor:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn temperature_monitor.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - sensor_static:/home/app/sensor/static
      - sensor_media:/home/app/sensor/media
    env_file:
      - ./.env.prod
    depends_on:
      - db


  db:
    image: postgres:12-alpine
    volumes:
      - sensor_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: unless-stopped


volumes:
  sensor_static:
  sensor_media:
  sensor_db_data:


